name: travel_crm
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  get: ^4.6.5
  flutter_bounce: ^1.1.0
  auto_size_text: ^3.0.0
  dropdown_button2: ^2.1.2
  dio: ^5.1.2
  flutter_easyloading: ^3.0.5
  hive: ^2.2.3
  intl: ^0.18.1
  pull_to_refresh: ^2.0.0
  image_picker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

 
  assets:
    - assets/Card_images/
    - assets/
    - assets/Flags/
    - assets/Icons/
    - assets/Images/
    - assets/Icons/master_settings/
    - assets/Icons/bottom_sheet/

